// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcm0e1YOnGKqO9mrDoh1dF1Nj19uf9Nr8',
    appId: '1:589729258614:web:6d799b1c9560d4e7241357',
    messagingSenderId: '589729258614',
    projectId: 'firebas-kepper',
    authDomain: 'firebas-kepper.firebaseapp.com',
    storageBucket: 'firebas-kepper.appspot.com',
    measurementId: 'G-LBQX4TNSHN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_oBYJN6N3eR_zqAqDw8KTakM99tO4tVo',
    appId: '1:589729258614:ios:87b8063b74809728241357',
    messagingSenderId: '589729258614',
    projectId: 'firebas-kepper',
    storageBucket: 'firebas-kepper.appspot.com',
    iosBundleId: 'com.example.firebaseKepper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oBYJN6N3eR_zqAqDw8KTakM99tO4tVo',
    appId: '1:589729258614:ios:87b8063b74809728241357',
    messagingSenderId: '589729258614',
    projectId: 'firebas-kepper',
    storageBucket: 'firebas-kepper.appspot.com',
    iosBundleId: 'com.example.firebaseKepper',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5zIfDRP9LOANNshLSV9shO482cX6Vnk',
    appId: '1:589729258614:android:eb6d8487f598c56b241357',
    messagingSenderId: '589729258614',
    projectId: 'firebas-kepper',
    storageBucket: 'firebas-kepper.appspot.com',
  );

}